---
# Handlers for webserver tasks

# Restart Apache
- name: "Restart apache"
  ansible.builtin.service:
    name: apache2
    state: restarted

# Restart Nginx
- name: "Restart Nginx"
  ansible.builtin.service:
    name: nginx
    state: restarted

# Validate Nginx configuration
- name: "Validate nginx configuration"
  ansible.builtin.command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: false

# Reload Nginx
- name: "Reload nginx"
  ansible.builtin.service:
    name: nginx
    state: reloaded
  when: "{{ nginx_service_state == 'started' }}"

# Add web server user to the Drupal user group
- name: "Add web server user to the Drupal user group"
  ansible.builtin.user:
    name: "{{ nginx_user }}"
    groups: "{{ drupal_user }}"
    append: yes
  become: true
