# Handlers for webserver tasks
- name: "Restart apache"
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: "Restart Nginx"
  ansible.builtin.service:
    name: nginx
    state: restarted
