---
- name: Deploy LAMP with Ansible
  hosts: localhost
  become: yes

  vars:
    php_version: "8.3"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Include tasks from common
      include_role:
        name: common

    - name: Include tasks from webserver
      include_role:
        name: webserver

    - name: Include tasks from php
      include_role:
        name: php
