---
# This playbook will deploy Drupa 10 on a LEMP stack.
# It will first setup the LEMP stack using the setup_lemp.yml playbook.
# Then it will install Drupal on the LEMP stack.

- name: Setup LEMP with Ansible
  import_playbook: setup_lemp.yml

- name: Install Drupal with Ansible
  hosts: all
  become: true

  tasks:
    - name: Download Drupal
      get_url:
        url: https://www.drupal.org/download-latest/zip
        dest: /tmp/drupal.zip

    - name: Unzip Drupal
      unarchive:
        src: /tmp/drupal.zip
        dest: /var/www/html
        extra_opts: [--strip-components=1]

    - name: Set permissions
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

    - name: Create Drupal settings file
      copy:
        dest: /var/www/html/sites/default/settings.php
        content: |
          <?php
          $databases['default']['default'] = array (
            'database' => 'drupal',
            'username' => 'drupaluser',
            'password' => 'drupalpass',
            'host' => 'localhost',
            'port' => '',
            'driver' => 'mysql',
            'prefix' => '',
          );

    - name: Create MySQL database
      mysql_db:
        name: drupal
        state: present

    - name: Create MySQL user
      mysql_user:
        name: drupaluser
        password: drupalpass
        priv: 'drupal.*:ALL'
        state: present
