---
# This playbook will deploy Drupa 10 on a LEMP stack.
# It will first setup the LEMP stack using the setup_lemp.yml playbook.
# Then it will install Drupal on the LEMP stack.

- name: Setup LEMP with Ansible
  import_playbook: setup_lemp.yml

- name: Install Drupal with Ansible
  hosts: localhost
  become: true

  roles:
    - role: drupal
      vars:
        drupal_version: "10"

  tasks:
    - name: Include Drupal role tasks
      ansible.builtin.include_role:
        name: drupal
