---
# This playbook will deploy Drupa 10 on a LEMP stack.
# - It will first setup the LEMP stack using the setup_lemp.yml playbook.
# - Then it will install a Drupal project on that LEMP stack.
# No drupal site will be created, just the project will be installed.

- name: Install Drupal project
  hosts: localhost
  connection: local
  become: true

  vars:
    # Drupal version
    drupal_version: "10.4.0"
    # Path to Drupal project
    drupal_path: "/var/www/drupal-{{ drupal_version }}"
    # TBD:
    # Drupal repository
    drupal_repo: "https://git.drupalcode.org/project/drupal"
    drupal_composer_project_package: "drupal/recommended-project:{{ drupal_version }}"
    # Composer project options
    drupal_composer_project_options: "--prefer-dist --stability dev --no-interaction"

  # All the main.yml files from each role will be included by default
  #   from defaults, variables, tasks and handlers
  roles:
    - role: drupal-project
    - role: user
    - role: composer
    - role: webserver

  # Tasks from roles to run
  tasks:
    - name: Create the drupal user
      include_role:
        name: user
        tasks_from: create-drupal-user

    - name: Install Drupal project
      include_role:
        name: composer
        tasks_from: install-drupal-project

  environment:
    COMPOSER_PROCESS_TIMEOUT: "1200"
    COMPOSER_MEMORY_LIMIT: "-1"
    COMPOSER_HOME: "{{ drupal_user_home }}/.composer"
