---
# This playbook will install a Drupal 10+ site into a Drupal project deployed by project_install.yml playbook.

# Usage:
# ansible-playbook site_install.yml --extra-vars "drupal_site_name=d1.example.com drupal_path=/path/to/drupal"

# Install Drupal site
- name: Install Drupal site
  hosts: localhost
  connection: local
  become: true

  vars_files:
    - vars/main.yml

  # Variables to pass to the role from command line
  vars:
    drupal_path: "{{ drupal_path }}"
    drupal_site_name: "{{ drupal_site_name }}"

  # Tasks from roles to run
  tasks:
    # Check if the directory for the Drupal site exists
    - name: Check if Drupal site directory exists
      ansible.builtin.stat:
        path: "{{ drupal_path }}/web/sites/{{ drupal_site_name }}"
      register: site_directory

    # Create the database user for the drupal site and install the Drupal site
    - name: Create database user and install Drupal site
      block:
        - name: Create database user for the site
          include_role:
            name: database
            tasks_from: create_db_user

        - name: Install the Drupal site
          include_role:
            name: drupal-site
            tasks_from: install-drupal-site
      when: site_directory.stat.exists == False

    # Update settings.php file
    - name: Update settings.php file
      include_role:
        name: drupal-site
        tasks_from: update-settings

    # Add site to the webserver
    - name: Add site to the webserver
      include_role:
        name: webserver
        tasks_from: add-site-config
