---
# This playbook will create the login URL for a Drupal 10+ site.

# Create site login URL
- name: Create site login URL
  hosts: localhost
  connection: local
  become: true

  vars_files:
    - vars/main.yml

  # Tasks from roles to run
  tasks:
    # Create the database user for the drupal site
    - name: Get site login URL
      include_role:
        name: drupal-site
        tasks_from: create-login-url
