---
# This playbook will install a Drupal 10+ site into a Drupal project deployed by project_install.yml playbook.

# Install Drupal site
- name: Install Drupal site
  hosts: localhost
  connection: local
  become: true

  vars_files:
    - vars/main.yml

  # Tasks from roles to run
  tasks:
    # Create the database user for the drupal site
    - name: Create database user for the site
      include_role:
        name: database
        tasks_from: create_db_user

    # Create the admin user of the site
    - name: Create admin user of the site
      include_role:
        name: drupal-site
        tasks_from: create-first-user

    # Install the Drupal site
    - name: Install the Drupal site
      include_role:
        name: drupal-site
        tasks_from: install-drupal-site

    # Add site to the webserver
    - name: Add site to the webserver
      include_role:
        name: webserver
        tasks_from: add-site
