---
# Common handlers

# Restart services
- name: Restart services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  with_items: "{{ services_to_restart }}"
  become: true
  become_user: root

# Clean up apt packages
- name: Clean up apt packages
  ansible.builtin.apt:
    autoclean: yes
    autoremove: yes
  become: true
  become_user: root
  when: ansible_os_family == 'Debian'
