---

# Ownership and permissions for Drupal web directory
docroot_permissions:
  - { name: "Set ownership", cmd: "find {{ drupal_path }}/web -exec chown {{ drupal_user }}:{{ nginx_user }} '{}' \\+" }
  - { name: "Set directory permissions", cmd: "find {{ drupal_path }}/web -type d -exec chmod 750 '{}' \\+" }
  - { name: "Set file permissions", cmd: "find {{ drupal_path }}/web -type f -exec chmod 640 '{}' \\+" }
