---
# Handlers for drupal-site tasks

- name: Set permissions for site directory
  ansible.builtin.command: >
    /usr/local/bin/site-ownership-permissions.sh
    --root="{{ drupal_path }}/web/sites/{{ drupal_site_name }}"
    --user="{{ drupal_user }}"
    --group="{{ drupal_user }}"
  args:
    chdir: "{{ drupal_path }}"
  become: true

# Settings files should have 440 permissions
- name: Apply 440 permissions to settings.php
  ansible.builtin.file:
    path: "{{ drupal_path }}/web/sites/{{ drupal_site_name }}/settings.php"
    mode: "0440"

# Reload Nginx
- name: "Reload nginx"
  ansible.builtin.service:
    name: nginx
    state: reloaded
  become: true
