---
# Common variables
apt_packages:
  - unzip
  - mc
services_to_restart:
  - "{{ webserver }}"
  - "php{{ php_version }}-fpm"
  - "{{ database }}"

root_user: "root"
root_group: "root"
root_home: "/root"

date: "{{ lookup('ansible.builtin.pipe', 'date +%y%m%d') }}"

# Drupal user
drupal_user: "da"
# .pub key for Drupal admin user: taken from system user ubuntu
drupal_user_pkey: "/home/ubuntu/.ssh/authorized_keys"
drupal_user_home: "/home/{{ drupal_user }}"


### Variables for composer
# Drupal version
drupal_version: "10.4.0"
# Path to the Drupal core
drupal_path: "/var/www/drupal-{{ drupal_version }}-{{ date }}"

# composer requirements added to Drupal project
# TBD: change name of the variable
drupal_composer_dependencies:
  - "drush/drush:^13.3"

# Global (system-wide) Composer
composer_version: "2.8.4" 
composer_path: "/usr/bin/composer"


###  Default variables for database
# db_root_password: "root"

# database: mysql or mariadb
database: "mysql"   # database: "mariadb"

# The default root user installed by mysql - almost always root
mysql_root_user: root
mysql_bind_address: 127.0.0.1
mysql_port: 3306
mysql_data_dir: /var/lib/mysql
mysql_unix_socket: /run/mysqld/mysqld.sock

# Custom settings
mysql_custom_settings:
  # Drupal10: change the MySQL transaction isolation level to READ COMMITTED
  # https://www.drupal.org/project/drupal/issues/1650930
  transaction-isolation: READ-COMMITTED
  #
  # CiviCRM: allows users to create stored functions and triggers without requiring the SUPER privilege
  # https://docs.civicrm.org/installation/en/latest/general/requirements/#binary-logging
  log_bin_trust_function_creators: 1


### Variables for PHP
php_version: "8.3"                # Define the PHP version to be used
date_timezone: "Europe/Budapest"  # Set the default timezone for PHP
max_execution_time: 240           # Set the maximum execution time for PHP scripts (in seconds)
max_input_time: 120               # Set the maximum input time for PHP scripts (in seconds)
post_max_size: "50M"              # Set the maximum size of POST data that PHP will accept
upload_max_filesize: "50M"        # Set the maximum size of uploaded files that PHP will accept
php_ini_path: "/etc/php/{{ php_version }}/fpm/php.ini" # Define default PHP configuration settings


### Variables for nginx
webserver: "nginx"
nginx_conf_path: "/etc/nginx/sites-available"
# Used only for Debian/Ubuntu installation, as the -t option for apt.
nginx_default_release: "noble"

# Use the official Nginx PPA for Ubuntu, and the version to use if so.
nginx_ppa_use: false
nginx_ppa_version: stable

# The name of the nginx package to install.
nginx_package_name: "nginx"

nginx_service_state: started
nginx_service_enabled: true

nginx_drupal_config_path: "/usr/local/etc/drupal/nginx"
nginx_conf_template: "nginx.conf.j2"
nginx_vhost_template: "vhost.j2"

nginx_worker_processes: >-
  "{{ ansible_processor_vcpus | default(ansible_processor_count) }}"
nginx_worker_connections: "1024"
nginx_multi_accept: "off"

nginx_error_log: "/var/log/nginx/error.log warn"
nginx_access_log: "/var/log/nginx/access.log main buffer=16k flush=2m"

nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"

nginx_keepalive_timeout: "75"
nginx_keepalive_requests: "600"

nginx_server_tokens: "on"

nginx_client_max_body_size: "64m"

nginx_server_names_hash_bucket_size: "64"

nginx_proxy_cache_path: ""

nginx_extra_conf_options: ""
# Example extra main options, used within the main nginx's context:
#   nginx_extra_conf_options: |
#     env VARIABLE;
#     include /etc/nginx/main.d/*.conf;

nginx_extra_http_options: ""
# Example extra http options, printed inside the main server http config:
#    nginx_extra_http_options: |
#      proxy_buffering    off;
#      proxy_set_header   X-Real-IP $remote_addr;
#      proxy_set_header   X-Scheme $scheme;
#      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
#      proxy_set_header   Host $http_host;

nginx_remove_default_vhost: false

# Listen on IPv6 (default: true)
nginx_listen_ipv6: true

nginx_vhosts: []
# Example vhost below, showing all available options:
# - listen: "80" # default: "80"
#   server_name: "example.com" # default: N/A
#   root: "/var/www/example.com" # default: N/A
#   index: "index.html index.htm" # default: "index.html index.htm"
#   filename: "example.com.conf" # Can be used to set the vhost filename.
#
#   # Properties that are only added if defined:
#   server_name_redirect: "www.example.com" # default: N/A
#   error_page: ""
#   access_log: ""
#   error_log: ""
#   extra_parameters: "" # Can be used to add extra config blocks (multiline).
#   template: "" # Can be used to override the `nginx_vhost_template` per host.
#   state: "absent" # To remove the vhost configuration.

nginx_upstreams: []
# - name: myapp1
#   strategy: "ip_hash" # "least_conn", etc.
#   keepalive: 16 # optional
#   servers:
#     - "srv1.example.com"
#     - "srv2.example.com weight=3"
#     - "srv3.example.com"

nginx_log_format: |-
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"'
