---
# Setup tasks for MySQL server

# Copy MySQL configurations.
- name: Copy MySQL global configuration
  ansible.builtin.template:
    src: mysql-global.conf.j2
    dest: /etc/mysql/mysql.cnf
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: "0644"
  notify: Restart MySQL

- name: Copy MySQL server configuration
  ansible.builtin.template:
    src: mysql-server.conf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: "0644"
  notify: Restart MySQL

- name: Copy MySQL client configuration
  ansible.builtin.template:
    src: mysql-client.conf.j2
    dest: /etc/mysql/mysql.conf.d/client.cnf
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: "0644"
  notify: Restart MySQL

# TBC!
- name: Ensure MySQL is running
  ansible.builtin.service:
    name: mysql
    state: started
