# Common tasks for php


# Apply PHP CLI configuration changes
- name: Set PHP CLI configuration values
  ansible.builtin.lineinfile:
    path: "/etc/php/{{ php_version }}/cli/php.ini"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop: "{{ php_configurations }}"
  notify: Restart PHP-FPM

# Apply PHP FPM configuration changes
- name: Set PHP FPM configuration values
  ansible.builtin.lineinfile:
    path: "/etc/php/{{ php_version }}/fpm/php.ini"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop: "{{ php_configurations }}"
  notify: Restart PHP-FPM
