---
# Setup tasks for MySQL server

# Variable setup.
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

# Install MySQL.
- name: "Install MySQL"
  ansible.builtin.apt:
    name: "mysql-server"
    state: present

# Copy MySQL configurations.
- name: Copy MySQL global configuration
  ansible.builtin.template:
    src: mysql.conf.j2
    dest: /etc/mysql/mysql.cnf
    owner: root
    group: root
    mode: '0644'
  notify: Restart MySQL

- name: Copy MySQL server configuration
  ansible.builtin.template:
    src: mysql-server.conf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: '0644'
  notify: Restart MySQL

- name: Copy MySQL client configuration
  ansible.builtin.template:
    src: mysql-client.conf.j2
    dest: /etc/mysql/mysql.conf.d/client.cnf
    owner: root
    group: root
    mode: '0644'
  notify: Restart MySQL

# TBC!
- name: Ensure MySQL is running
  ansible.builtin.service:
    name: mysql
    state: started
