all:
  vars:
    ansible_user: ansible
    ansible_python_interpreter: "/usr/bin/python3"
    localhost:
      ansible_connection: local

  children:
    lts2404:
      hosts:
        m01:
        m02:
        m03:
        m04:
    webservers:
      hosts:
        m01:
        m02:
        m03:
        m04:
    dbservers:
      hosts:
        m01:
        m02:
        m03:
        m04:
    # clients cannot share servers!!!
    clientA:
      hosts:
        m01:
        m03:
    clientB:
      hosts:
        m02:
