all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
    control:
      hosts: {}
    clientAP:
      hosts: {}
    clientMH:
      hosts: {}
    managed:
      hosts: {}
    secured:
      hosts: {}
    lamp:
      hosts: {}
    lts2404:
      hosts: {}
    dev:
      children:
        clientAP: {}
        clientMH: {}
      hosts: {}
