all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
  vars:
    ansible_user: ansible
    ansible_python_interpreter: "/usr/bin/python3"
  children:
    lts2404:
      hosts:
        m01:
        m02:
        m03:
        m04:
        ctr01:
    control:
      hosts:
        ctr01:
    webservers:
      hosts:
        m01:
        m02:
        m03:
        m04:
    dbservers:
      hosts:
        m01:
        m02:
        m03:
        m04:
    # clients cannot share servers!!!
    clientA:
      hosts:
        m01:
        m03:
    clientB:
      hosts:
        m02:
