all:
  vars:
    ansible_user: ansible
    ansible_python_interpreter: "/usr/bin/python3"
    localhost:
      ansible_connection: local

  children:
    lts2404:
      hosts:
        m01:
        m02:
        m03:
        m04:
        ctr01:
    control:
      hosts:
        ctr01:
    webservers:
      hosts:
        m01:
        m02:
        m03:
        m04:
    dbservers:
      hosts:
        m01:
        m02:
        m03:
        m04:
    # clients cannot share servers!!!
    clientA:
      vars:
        # Read variables from vault file
        vault_vars: "{{ lookup('file', ansible_vault_file) | from_yaml }}"
      hosts:
        m01:
        m03:
    clientB:
      vars:
        # Read variables from vault file
        vault_vars: "{{ lookup('file', ansible_vault_file) | from_yaml }}"
      hosts:
        m02:
