# check syntax: ansible-inventory --list

all:
  hosts:
    m1:  #m1
      ansible_host: 192.168.64.244
      ansible_user: ansible
    m2:  #m2
      ansible_host: 192.168.64.245
      ansible_user: ansible
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "/usr/bin/python3"

  children:
    # variables go into respective group and host variable files
    lemp:
      hosts:
        m1:
        m2:

    drupal:
      hosts:
        m1:
        m2:

    sites:
      hosts:
        m1:
        m2:
