---

# Allow write permissions for webserver user for sites/{{ site_dir }} directory
sites_permissions:
  - { name: "Set ownership", cmd: "find {{ drupal_path }}/web/sites/{{ site_dir }} -exec chown {{ drupal_user }}:{{ nginx_user }} '{}' \\+" }
  - { name: "Set directory permissions", cmd: "find {{ drupal_path }}/web/sites/{{ site_dir }} -type d -exec chmod 750 '{}' \\+" }
  - { name: "Set file permissions", cmd: "find {{ drupal_path }}/web/sites/{{ site_dir }} -type f -exec chmod 640 '{}' \\+" }
