---
# Manage vhost configuration files.

# Remove default vhost config file.
- name: Remove default nginx vhost config file (if configured).
  ansible.builtin.file:
    path: "{{ nginx_default_vhost_path }}"
    state: absent
  notify: Reload nginx

# Ensure vhost path exists.
- name: Ensure nginx_vhost_path exists.
  ansible.builtin.file:
    path: "{{ nginx_vhost_path }}"
    state: directory
    mode: "0755"
  notify: Reload nginx

# Check if the directory for the Drupal site exists
- name: Check if Drupal site directory exists
  ansible.builtin.stat:
    path: "{{ drupal_path }}/web/sites/{{ drupal_site_name }}"
  register: site_directory

# Add vhost config files.
- name: Add managed vhost config files.
  ansible.builtin.template:
    src: site.conf.j2
    dest: "{{ nginx_vhost_path }}/{{ item.server_name }}.conf"
    force: true
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: "0644"
  with_items: "{{ nginx_vhosts }}"
  notify: Restart services
  when: site_directory.stat.exists == True
