---
# This task will setup all new Drupal sites.

# Log site information
- name: Log site information
  ansible.builtin.debug:
    msg: "Site: {{ item.key }}, Server: {{ sites[item.key].server }}, Platform: {{ sites[item.key].platform }}"
 
# Check if it runs on the specified platform
- name: Check presence of platform
  ansible.builtin.assert:
    that: 
      - platforms[ sites[item.key].platform ].name == sites[item.key].platform
    fail_msg: "Defined platform for site {{ item.key }} is not present on the server."
  register: platform

# Check if the site already exists within the platform
- name: Check if Drupal site exists
  ansible.builtin.stat:
    path: "{{ platforms[ sites[item.key].platform ].path }}{{ platforms[ sites[item.key].platform ].name }}/web/sites/{{ sites[item.key].name }}"
  register: site_exists
  when: platform is not failed

# Create a new site if it does not exist
- name: Install new site
  include_tasks: install-site-drush.yml
  when: platform is not failed and not site_exists.stat.exists

# Create login URL for the site
- name: Create login URL
  include_tasks: create-login-url.yml
  when: platform is not failed and not site_exists.stat.exists

# Log message if the site already exists
- name: Log message if site already exists
  ansible.builtin.debug:
    msg: "Site {{ sites[item.key].name }} already exists."
  when: platform is not failed and site_exists.stat.exists
