---
# Install a Drupal site with drush

# Set variables for the Drupal site
- name: Set variables for the Drupal site 1
  ansible.builtin.set_fact:
    platform_user: "{{ platforms[ sites[item.key].platform ].user }}"
    platform_group: "{{ platforms[ sites[item.key].platform ].group }}"
    platform_path: "{{ platforms[ sites[item.key].platform ].path }}{{ platforms[ sites[item.key].platform ].name }}"
    install_profile: "{{ platforms[ sites[item.key].platform ].profile | default('standard') }}"
    site_name: "{{ sites[item.key].name }}"
    site_user: "{{ sites[item.key].user | default('admin') }}"
    site_pass: "{{ lookup('ansible.builtin.password', '/dev/null', length=20 + (5 | random), chars=['ascii_letters', 'digits', '!+-.:<=>_|']) }}"
    db_pass: "{{ lookup('ansible.builtin.password', '/dev/null', length=16, chars=['ascii_letters', 'digits', '!+-.:<=>_|']) }}"
    db_host: "localhost"
    db_backend: "mysql" 
    extra_args: "{{ drupal_site_install_extra_args | join(' ') }}"
    modules: "{{ sites[item.key].modules | join(' ') }}"
# Set variables for the Drupal site reusing the previous variables
- name: Set variables for the Drupal site reusing the previous variables
  ansible.builtin.set_fact:
    drush_path: "{{ platform_path }}/vendor/bin/drush"
    db_user: "{{ site_name | regex_replace('[^a-zA-Z0-9]', '') }}"  # Remove special characters
    db_name: "{{ site_name | regex_replace('[^a-zA-Z0-9]', '') }}"

# Create database user for site
- name: Create database user for site
  community.mysql.mysql_user:
    check_implicit_admin: true
    login_unix_socket: "{{ mysql_unix_socket }}"
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    priv: "*.*:ALL,GRANT"
    host: "{{ db_host }}"
    state: present
  become: true
 
# Install Drupal core with drush only if sites have not been installed
- name: Install Drupal core with drush.
  ansible.builtin.command: >
    {{ drush_path }} --root={{ platform_path }} site-install {{ install_profile }} -y
    --site-name="{{ site_name }}"
    --sites-subdir="{{ site_name }}"
    --account-name="{{ site_user }}"
    --account-pass="{{ site_pass }}"
    --db-url={{ db_backend }}://{{ db_user }}:{{ db_pass }}@{{ db_host }}/{{ db_name }}
    {{ extra_args }}
  args:
    chdir: "{{ platform_path }}"
  become: true

# Install Drupal modules with drush
- name: Install Drupal modules with drush.
  ansible.builtin.command: >
    {{ drush_path }} pm-enable -y {{ modules }} --uri={{ site_name }} --root={{ platform_path }}
  args:
    chdir: "{{ platform_path }}"
  become: true
