---
# Install Drupal site

# Generate a random password for the Drupal site user
- name: Generate a random password for the Drupal site user
  ansible.builtin.set_fact:
    drupal_site_pass: "{{ lookup('ansible.builtin.password', '/dev/null', length=16, chars=['ascii_letters', 'digits', 'punctuation']) }}"

# Install Drupal core with drush
- name: Install Drupal core with drush.
  ansible.builtin.command: >
    {{ drush_path_site }} --root={{ drupal_path }} site-install {{ drupal_install_profile | default('standard') }} -y
    --site-name="{{ drupal_site_name }}"
    --sites-subdir="{{ drupal_site_name }}"
    --account-name="{{ drupal_site_user }}"
    --account-pass={{ drupal_site_pass }}
    --db-url={{ drupal_db_backend }}://{{ drupal_db_user }}:{{ drupal_db_password }}@{{ drupal_db_host }}/{{ drupal_db_name }}
    {{ drupal_site_install_extra_args | join(" ") }}
  args:
    chdir: "{{ drupal_path }}"
  notify: Set permissions for site directory
  # TBD: when: "'Drupal bootstrap' not in drupal_site_installed.stdout"
  become: true
  become_user: "{{ drupal_user }}"

# Install Drupal modules with drush
- name: Install Drupal modules with drush.
  ansible.builtin.command: >
    {{ drush_path_site }} pm-enable -y {{ drupal_enable_modules | join(" ") }} --uri={{ drupal_site_name }}
    --root={{ drupal_path }}
  args:
    chdir: "{{ drupal_path }}"
  # TBD: when: ('Drupal bootstrap' not in drupal_site_installed.stdout) and drupal_enable_modules
  become: false
