---
# Install Drupal site

# Check if any Drupal site has been installed within the drupal_path
- name: Find installed drupal site(s)
  ansible.builtin.find:
    paths: "{{ drupal_path }}/web/sites/{{ drupal_site_name }}"
    patterns: "settings.php"
    use_regex: yes
  register: site_installed

# Generate a random password for the Drupal site user
- name: Create a password
  ansible.builtin.set_fact:
    drupal_site_pass: "{{ lookup('ansible.builtin.password', length=20 + (5 | random), chars=['ascii_letters', 'digits', '!+-_']) }}"
  no_log: true

# Install Drupal core with drush only if sites have not been installed
- name: Install Drupal core with drush.
  ansible.builtin.command: >
    {{ drush_path_site }} --root={{ drupal_path }} site-install {{ drupal_install_profile | default('standard') }} -y
    --site-name="{{ drupal_site_name }}"
    --sites-subdir="{{ drupal_site_name }}"
    --account-name="{{ drupal_site_user }}"
    --account-pass={{ drupal_site_pass }}
    --db-url={{ drupal_db_backend }}://{{ drupal_db_user }}:{{ drupal_db_password }}@{{ drupal_db_host }}/{{ drupal_db_name }}
    {{ drupal_site_install_extra_args | join(" ") }}
  args:
    chdir: "{{ drupal_path }}"
  notify: Set permissions for site directory
  when: site_installed.matched == 0
  become: true
  become_user: "{{ drupal_user }}"

# Install Drupal modules with drush
- name: Install Drupal modules with drush.
  ansible.builtin.command: >
    {{ drush_path_site }} pm-enable -y {{ drupal_enable_modules | join(" ") }} --uri={{ drupal_site_name }}
    --root={{ drupal_path }}
  args:
    chdir: "{{ drupal_path }}"
  # TBD: when: ('Drupal bootstrap' not in drupal_site_installed.stdout) and drupal_enable_modules
  become: false
