# Ansible host variables for local-aegir
# Secrets in inventory/dev/host_vars/local-aegir/vault.yml

ansible_host: "{{ vault_local_aegir.ip }}"
ansible_port: "{{ vault_local_aegir.port }}"
fqdn: "{{ vault_local_aegir.fqdn }}"
hardware: "{{ vault_local_aegir.hardware }}"
cloudflare_enabled: false
vscode_enabled: true
host_secured: true
data_volume_root: "/var/aegir"

# Client info
env: dev               # environment for playbooks
client_name: aegir     # client name for playbooks

# host-specific SSH users
ssh_users:
  - "{{ vault_local_aegir.ssh_users.dev | default('') }}"
  - "{{ vault_local_aegir.ssh_users.os  | default('') }}"

# LAMP stack
stack:
  os: ubuntu-24
  php: php-83
  mysql: mysql-80
  apache: apache-24
  drupal: drupal11.3

platforms:
  drupal11.3:
    user: drupal11_3
    group: drupal11_3
  aegir-2601:
    user: aegir
    group: aegir
