---

- name: Install dependencies with composer require
  community.general.composer:
    command: require
    arguments: "{{ item }}"
    working_dir: "{{ drupal_path }}"
  with_items: "{{ drupal_composer_dependencies | default([]) }}"
  become: true
  become_user: "{{ drupal_user }}"
