---

# Ensure the destination directory exists
- name: Create destination directory for Nginx configuration
  ansible.builtin.file:
    path: "{{ nginx_drupal_config_path }}"
    state: directory
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: '0755'

# Copy Drupal configuration for Nginx.
- name: Copy Drupal configuration for Nginx
  ansible.builtin.template:
    src: drupal.conf.j2
    dest: "{{ nginx_drupal_config_path }}/drupal.conf"
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: '0644'
  notify: Restart Nginx
