---
# Deploy Drupal 10 using Composer

- name: Delete old /tmp/composer-project
  ansible.builtin.file:
    path: "/tmp/composer-project"
    state: absent

- name: Generate Drupal project with composer package
  community.general.composer:
    command: create-project
    arguments: "{{ drupal_composer_project_package }} /tmp/composer-project {{ drupal_composer_project_options }}"
    working_dir: "/tmp"
    optimize_autoloader: yes
  become: true
  become_user: "{{ drupal_user }}"

- name: Ensure project root exists and has proper permissions.
  ansible.builtin.file:
    path: "{{ drupal_path }}"
    state: directory
    owner: "{{ drupal_user }}"
    group: "{{ drupal_user }}"
    mode: "{{ project_root_permissions }}"

- name: Move Drupal project files to project root
  ansible.builtin.command: >
    cp -r /tmp/composer-project/. {{ drupal_path }}/
    creates={{ drupal_docroot }}/index.php
  become: true
  become_user: "{{ drupal_user }}"
  notify: Set ownership and file permissions for a Drupal project
  failed_when: false
