---
# This playbook creates all users defined in the platforms variable with SSH login only, bash shell, home directory, without password login, and with sudo rights.

- name: Create group for user
  ansible.builtin.group:
    name: "{{ item.value.group }}"
    state: present

# Add web server user to the project user group
- name: "Add web server user to the project user group"
  ansible.builtin.user:
    name: "{{ nginx_user }}"
    groups: "{{ item.value.group }}"
    append: yes
  become: true

- name: Create platform users
  ansible.builtin.user:
    name: "{{ item.value.user }}"
    state: present
    home: "/home/{{ item.value.user }}"
    group: "{{ item.value.group }}"
    shell: /bin/bash
    password_lock: true

- name: Add SSH key for platform users
  ansible.posix.authorized_key:
    user: "{{ item.value.user }}"
    key: "{{ lookup('file', '/home/{{ ansible_user }}/.ssh/authorized_keys') }}"
    state: present
  when: not ansible_check_mode

- name: Add platform users to sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^{{ item.value.user }} "
    line: "{{ item.value.user }} ALL=(ALL) NOPASSWD:ALL"

# Add backup directory for platform users
- name: Add backup directory for platform users
  ansible.builtin.file:
    path: "/home/{{ item.value.user }}/backup"
    state: directory
    owner: "{{ item.value.user }}"
    group: "{{ item.value.group }}"
    mode: "0750"
  become: true
