# Handlers for database tasks
- name: "Restart MariaDB"
  ansible.builtin.service:
    name: mariadb
    state: restarted

- name: "Restart MySQL"
  ansible.builtin.service:
    name: mysql-server
    state: restarted
