# Common tasks for php

- name: "Add PHP repository for Nginx"
  ansible.builtin.apt_repository:
    repo: 'ppa:ondrej/nginx'
    update_cache: true

- name: "Install PHP for CiviCRM"
  ansible.builtin.apt:
    state: present
    name:
      - "php{{ php_version }}"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-zip"
      - "php{{ php_version }}-bcmath"
      - "php{{ php_version }}-intl"
      - "php{{ php_version }}-soap"

- name: "Install global Composer"
  ansible.builtin.get_url:
    url: https://getcomposer.org/download/{{ composer_version }}/composer.phar
    dest: /usr/bin/composer
    mode: "0775"
