---
# Setup tasks for Nginx webserver

# Variable setup.
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

# Install Nginx.
- name: "Install Nginx"
  ansible.builtin.apt:
    name: "nginx"
    state: present

# Copy Nginx configuration.
- name: Copy Nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: '0644'
  notify: Restart Nginx
