---
# Variables for client sites

client: "clientB"

sites:
  c2_example_com:
    name: "c2.example.com"
    server: m02
    platform: drupal10
    modules:
      - "admin_toolbar"
      - "pathauto"
    # from vault file, encrypted with ansible-vault
    cf:
      zone_id: "{{ c2.zone_id | default('dummy') }}"
      email: "{{ c2.email | default('dummy') }}"
      api_key: "{{ c2.api_key | default('dummy') }}"
      private_key: "{{ c2.key | default('dummy') }}"
  
  c4_example_com:
    name: "c4.example.com"
    server: m02
    platform: drupal11
    modules: []
    # from vault file, encrypted with ansible-vault
    cf:
      zone_id: "{{ c4.zone_id | default('dummy') }}"
      email: "{{ c4.email | default('dummy') }}"
      api_key: "{{ c4.api_key | default('dummy') }}"
      private_key: "{{ c4.key | default('dummy') }}"
