---
# Variables for LEMP servers

### Variables for the webserver role
# webserver: ningx or apache2
webserver: nginx
# webserver: apache2

###  Variables for the PHP role
# Define the PHP version to be used
php_version: "8.3"

###  Variables for the database role
# database: mysql or mariadb
database: "mysql"
# database: "mariadb"
# Database Configuration
drupal_db_backend: "{{ database }}"
drupal_db_host: "localhost"


# Ubuntu and Debian specific variables for Nginx
nginx_conf_path: /etc/nginx/conf.d
nginx_conf_file_path: /etc/nginx/nginx.conf
nginx_mime_file_path: /etc/nginx/mime.types
nginx_pidfile: /run/nginx.pid
nginx_vhost_path: /etc/nginx/sites-enabled
nginx_default_vhost_path: /etc/nginx/sites-enabled/default
nginx_user: "www-data"

# Admin User in OS
root_user: "root"
root_group: "root"
root_home: "/root"

# Composer Configuration
composer_version: "2.8.4"
composer_path: "/usr/bin/composer"

### Variables for the common role
# OS packages to install
apt_packages:
  - unzip
  - mc
  - acl # Ansible requires setfacl from this package to manage temporary file permissions when switching users.
