---
# Handlers for drupal-site tasks

- name: Set permissions for site directory
  ansible.builtin.command: >
    /usr/local/bin/site-ownership-permissions.sh
    --root="{{ drupal_path }}/web/sites/{{ drupal_site_name }}"
    --user="{{ drupal_user }}"
    --group="{{ nginx_user }}"
  args:
    chdir: "{{ drupal_path }}"
  become: true
