---
# Deploy Drupal 10 using Composer

- name: Delete old /tmp/composer-project
  ansible.builtin.file:
    path: "/tmp/composer-project"
    state: absent

- name: Generate Drupal project with composer package
  community.general.composer:
    command: create-project
    arguments: "{{ drupal_composer_project_package }} /tmp/composer-project {{ drupal_composer_project_options }}"
    working_dir: "/tmp"
  become: true
  become_user: "{{ drupal_admin_user }}"

- name: Ensure drupal_path exists and has proper permissions.
  ansible.builtin.file:
    path: "{{ drupal_path }}"
    state: directory
    owner: "{{ drupal_admin_user }}"
    group: "{{ drupal_admin_user }}"
    mode: "0775"

- name: Move Drupal project files to drupal_path
  ansible.builtin.command: >
    cp -r /tmp/composer-project/. {{ drupal_path }}/
    creates={{ drupal_docroot }}/index.php
  become: true
  become_user: "{{ drupal_admin_user }}"
  notify: Set ownership and file permissions for Drupal web directory
  failed_when: false

- name: Install dependencies with composer require
  community.general.composer:
    command: require
    arguments: "{{ item }}"
    working_dir: "{{ drupal_path }}"
  with_items: "{{ drupal_composer_dependencies | default([]) }}"
  become: true
  become_user: "{{ drupal_admin_user }}"
