---
# Common tasks for drupal

# Create drupal admin user.
- name: Create drupal admin user
  ansible.builtin.include_tasks: create-admin-user.yml

# Setup drush
- name: Setup drush
  ansible.builtin.include_tasks: setup-drush.yml

# Deploy Drupal code with composer.
- name: Deploy Drupal codebase with Composer
  ansible.builtin.include_tasks: composer-deploy.yml

- name: Install site if configured.
  ansible.builtin.include_tasks: install-site.yml
  #  when: drupal_install_site