---
- name: Deploy Drupal with Ansible
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - php-gd
          - php-xml
          - php-mbstring
          - libapache2-mod-php
          - unzip
        state: present

    - name: Enable Apache rewrite module
      command: a2enmod rewrite

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

    - name: Download Drupal
      get_url:
        url: https://www.drupal.org/download-latest/zip
        dest: /tmp/drupal.zip

    - name: Unzip Drupal
      unarchive:
        src: /tmp/drupal.zip
        dest: /var/www/html
        extra_opts: [--strip-components=1]

    - name: Set permissions
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

    - name: Create Drupal settings file
      copy:
        dest: /var/www/html/sites/default/settings.php
        content: |
          <?php
          $databases['default']['default'] = array (
            'database' => 'drupal',
            'username' => 'drupaluser',
            'password' => 'drupalpass',
            'host' => 'localhost',
            'port' => '',
            'driver' => 'mysql',
            'prefix' => '',
          );

    - name: Create MySQL database
      mysql_db:
        name: drupal
        state: present

    - name: Create MySQL user
      mysql_user:
        name: drupaluser
        password: drupalpass
        priv: 'drupal.*:ALL'
        state: present
