---
- name: Setup LEMP with Ansible
  hosts: localhost
  become: true

  vars:
    root_user: "{{ root_user }}"
    root_group: "{{ root_group }}"

  tasks:
    - name: Setup LEMP stack
      include_role:
        name: server
