---
# This playbook sets up a LEMP stack using Ansible

- name: Setup LEMP with Ansible
  hosts: localhost
  become: true

  vars_files:
    - vars/main.yml

  tasks:
    - name: Setup LEMP stack
      include_role:
        name: server
