---
- name: Setup LEMP with Ansible
  hosts: localhost
  become: true

  vars_files:
    - vars/main.yml

  tasks:
    - name: Install packages
      include_role:
        name: common
        tasks_from: apt-install-packages

    - name: Install scripts
      include_role:
        name: common
        tasks_from: install-scripts

    - name: Install webserver
      include_role:
        name: webserver
        tasks_from: install-webserver

    - name: Install PHP
      include_role:
        name: php
        tasks_from: setup-php

    - name: Install database
      include_role:
        name: database
        tasks_from: setup_dbserver

    - name: Install composer
      include_role:
        name: composer
        tasks_from: install-global-composer
