---
######
# 
# This Ansible playbook is designed to set up a new Drupal project on a local machine.
#
# Usage:
# ansible-playbook project.yml --extra-vars "drupal_project_name=drupal10 drupal_user=da"

- name: Setup Drupal project with Ansible
  hosts: localhost
  become: true

  vars_files:
    - ../vars/main.yml
  
  # Variables to pass to the playbook from command line
  vars:
    drupal_project_name: "{{ drupal_project_name }}"   # Used as directory name /var/www/drupla10, e.g. drupal10
    drupal_user: "{{ drupal_user }}"                   # OS user for this project, e.g. drupal

  tasks:
    # set drupal_path to the path to the Drupal core
    - set_fact:
        drupal_path: "/var/www/{{ drupal_project_name }}"
    
    # Setup the server
    - name: Setup LEMP stack
      include_role:
        name: server

    # Setup the drupal codebase
    - name: Setup Drupal project
      include_role:
        name: project

  environment:
    COMPOSER_PROCESS_TIMEOUT: "1200"
    COMPOSER_MEMORY_LIMIT: "-1"
    COMPOSER_HOME: "{{ drupal_user_home }}/.composer"
