---
# This playbook will deploy Drupal 10+ on a LEMP stack, deployed by lemp_setup.yml playbook.
# It will install a Drupal project, but no drupal site will be created, see: site_install.yml

# Install Drupal project
- name: Install Drupal project
  hosts: localhost
  connection: local
  become: true

  vars_files:
    - vars/main.yml

  # All the main.yml files from each role will be included by default
  # Needed for defaults, variables, handlers, etc.
  roles:
  - role: webserver

  # Tasks from roles to run
  tasks:
    # Create the drupal user if it does not exist
    - name: Create the drupal user
      include_role:
        name: user
        tasks_from: create-drupal-user

    # Add drupal.conf to webserver
    - name: Add Drupal configuration to webserver
      include_role:
        name: webserver
        tasks_from: add-project-config

    # Check if any Drupal site has been installed within the drupal_path
    - name: Find installed drupal site(s)
      ansible.builtin.find:
        paths: "{{ drupal_path }}/web/sites"
        patterns: "settings.php"
        recurse: yes
        use_regex: yes
        excludes: "default"
      register: drupal_site_installed

    # Install the Drupal project only if sites have not been installed
    - name: Install Drupal project
      include_role:
        name: drupal-project
        tasks_from: install-drupal-project
      when: drupal_site_installed.matched == 0

    # Add composer requirements to project
    - name: Add composer requirements
      include_role:
        name: composer
        tasks_from: add-composer-requirements
      when: drupal_site_installed.matched == 0

  environment:
    COMPOSER_PROCESS_TIMEOUT: "1200"
    COMPOSER_MEMORY_LIMIT: "-1"
    COMPOSER_HOME: "{{ project_user_home }}/.composer"
