---
- name: Setup Drupal project with Ansible
  hosts: localhost
  become: true

  vars_files:
    - ../vars/main.yml

  tasks:
    - name: Setup LEMP stack
      include_role:
        name: server

    - name: Setup Drupal project
      include_role:
        name: project
  environment:
    COMPOSER_PROCESS_TIMEOUT: "1200"
    COMPOSER_MEMORY_LIMIT: "-1"
    COMPOSER_HOME: "{{ drupal_user_home }}/.composer"
