---
######
# 
# This Ansible playbook is designed to set up a new Drupal project.
#
# Usage:
# ansible-playbook project.yml --extra-vars "drupal_project_name=drupal10 project_user=da"

- name: Setup Drupal project with Ansible
  hosts: drupal
  become: true

  tasks:
    # set drupal_path to the path to the Drupal core
    - set_fact:
        drupal_path: "/var/www/{{ drupal_project_name }}"
    
    # Setup the server
    - name: Setup LEMP stack
      include_role:
        name: server

    # Setup the drupal codebase
    - name: Setup Drupal project
      include_role:
        name: project

  environment:
    COMPOSER_PROCESS_TIMEOUT: "1200"
    COMPOSER_MEMORY_LIMIT: "-1"
    COMPOSER_HOME: "{{ project_user_home }}/.composer"
