---
# This playbook will create the login URL for a Drupal 10+ site.

# Usage:
# ansible-playbook site_login.yml --extra-vars "drupal_project_name=drupal10 drupal_site_name=d1.example.com"

# Create site login URL
- name: Create site login URL
  hosts: drupal
  connection: local
  become: true

  vars_files:
    - ../vars/main.yml

  # Variables to pass to the role from command line
  vars:
    drupal_site_name: "{{ drupal_site_name }}"         # Used as directory name /var/www/drupla10/web/sites/d1.example.com, e.g. d1.example.com
    drupal_project_name: "{{ drupal_project_name }}"   # Used as directory name /var/www/drupla10, e.g. drupal10

  # Tasks from roles to run
  tasks:
    # set drupal_path based on the project name
    - set_fact:
        drupal_path: "/var/www/{{ drupal_project_name }}"

    # Create the database user for the drupal site
    - name: Get site login URL
      include_role:
        name: site
        tasks_from: create-login-url
