---
######
# 
# This Ansible playbook is designed to set up a Drupal site.
#
# Usage:
# ansible-playbook site.yml --extra-vars "drupal_project_name=drupal10 drupal_site_name=d1.example.com"

- name: Setup a Drupal site with Ansible
  hosts: sites
  become: true

  tasks:
    # set drupal_path to the path to the Drupal core
    - set_fact:
        drupal_path: "/var/www/{{ drupal_project_name }}"

    - name: Setup LEMP stack
      include_role:
        name: server

    - name: Setup Drupal project
      include_role:
        name: project
    # This task is required to trigger the handlers defined in the project role
    - name: Trigger pending handlers
      meta: flush_handlers  # Handlers execute here

    - name: Setup Drupal site
      include_role:
        name: site

  environment:
    COMPOSER_PROCESS_TIMEOUT: "1200"
    COMPOSER_MEMORY_LIMIT: "-1"
    COMPOSER_HOME: "{{ project_user_home }}/.composer"
