---
######
# 
# This playbook is about operations on Drupal 10/11 sites
# 
# It does the following:
# - creates specified new sites if does not exist:              --tags install
# - verifies configuration for existing sites                   --tags verify
# - resets password for a site                                  --tags reset-password
# - delete specified site                                       --tags delete
# - updates code and database for existing sites                --tags update
# - backs up specified site                                     --tags backup
# - restores specified site for a date                          --tags restore
# - setup ssl certificate for a site                            --tags ssl
# TBD:
# - runs cron jobs for sites (??? - not sure if this is needed) --tags cron
# - migrates/clones site to an other platform                   --tags migrate or clone ?
#
# Use tags to run specific operation:
#   ansible-playbook playbooks/sites.yml --tags verify
#   ansible-playbook playbooks/sites.yml --tags reset-password --extra-vars "site=c1.example.com"
#   ansible-playbook playbooks/sites.yml --tags delete         --extra-vars "site=c1.example.com"
#   ansible-playbook playbooks/sites.yml --tags restore        --extra-vars "site=c1.example.com arch=250322"
#   ansible-playbook playbooks/sites.yml --tags ssl            --extra-vars "site=c1.example.com"

- name: Drupal sites operations
  hosts: 
    - clientA
    - clientB
  become: true

  # Encrypted variables, like cloudflare API key, ...
  vars_files:
    - "../inventory/{{ env }}/group_vars/vaultvars.yml"

  # Variables to pass to the role from command line
  vars:
    site_name: "{{ site }}"         # Used for password reset, e.g. c1.example.com
    date: "{{ arch | default(lookup('ansible.builtin.pipe', 'date +%y%m%d')) }}"         # Used as restore date
    target_platform: "{{ target }}" # Used for migration

  tasks:
    # Run tasks of the site role as defined by tags
    - name: Drupal site operations
      include_role:
        name: site
      tags: 
        - verify
        - install
        - reset-password
        - delete
        - update
        - backup
        - restore
        - migrate
        - ssl
        - never  # This tag is used to prevent running the task without a tag
