---
######
# 
# This Ansible playbook is designed to set up a Drupal site on a local machine.
#
# Usage:
# ansible-playbook site.yml --extra-vars "drupal_project_name=drupal10 drupal_site_name=d1.example.com"

- name: Setup a Drupal site with Ansible
  hosts: drupal
  become: true

  vars_files:
    - ../vars/main.yml

  # Variables to pass to the playbook from command line
  vars:
    drupal_site_name: "{{ drupal_site_name }}"         # Used as directory name /var/www/drupal10/web/sites/d1.example.com, e.g. d1.example.com
    drupal_project_name: "{{ drupal_project_name }}"   # Used as directory name /var/www/drupal10, e.g. drupal10

  tasks:
    # set drupal_path to the path to the Drupal core
    - set_fact:
        drupal_path: "/var/www/{{ drupal_project_name }}"

    - name: Setup LEMP stack
      include_role:
        name: server

    - name: Setup Drupal project
      include_role:
        name: project

    - name: Setup Drupal site
      include_role:
        name: site

  environment:
    COMPOSER_PROCESS_TIMEOUT: "1200"
    COMPOSER_MEMORY_LIMIT: "-1"
    COMPOSER_HOME: "{{ project_user_home }}/.composer"
